// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAdminSession = `-- name: CreateAdminSession :exec
INSERT INTO admin_sessions (id, email, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateAdminSessionParams struct {
	ID        uuid.UUID
	Email     string
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAdminSession,
		arg.ID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createMagicLink = `-- name: CreateMagicLink :exec
INSERT INTO magic_links (id, email, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateMagicLinkParams struct {
	ID        uuid.UUID
	Email     string
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) error {
	_, err := q.db.ExecContext(ctx, createMagicLink,
		arg.ID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM admin_sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteTester = `-- name: DeleteTester :exec
DELETE FROM tester_signups WHERE id = $1
`

func (q *Queries) DeleteTester(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTester, id)
	return err
}

const findValidMagicLinkForUpdate = `-- name: FindValidMagicLinkForUpdate :one
SELECT email
FROM magic_links
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > NOW()
    FOR UPDATE
`

func (q *Queries) FindValidMagicLinkForUpdate(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRowContext(ctx, findValidMagicLinkForUpdate, tokenHash)
	var email string
	err := row.Scan(&email)
	return email, err
}

const findValidSession = `-- name: FindValidSession :one
SELECT email
FROM admin_sessions
WHERE token_hash = $1
  AND expires_at > NOW()
`

func (q *Queries) FindValidSession(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRowContext(ctx, findValidSession, tokenHash)
	var email string
	err := row.Scan(&email)
	return email, err
}

const isAdminWhitelisted = `-- name: IsAdminWhitelisted :one
SELECT EXISTS (
    SELECT 1 FROM admin_whitelist WHERE email = $1
)
`

func (q *Queries) IsAdminWhitelisted(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAdminWhitelisted, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markMagicLinkUsed = `-- name: MarkMagicLinkUsed :exec
UPDATE magic_links
SET used_at = NOW()
WHERE token_hash = $1
`

func (q *Queries) MarkMagicLinkUsed(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, markMagicLinkUsed, tokenHash)
	return err
}
