// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AdminSession struct {
	ID        uuid.UUID
	Email     string
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type AdminWhitelist struct {
	ID        uuid.UUID
	Email     string
	CreatedAt time.Time
}

type MagicLink struct {
	ID        uuid.UUID
	Email     string
	TokenHash string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type TesterSignup struct {
	ID         uuid.UUID
	Email      string
	Name       string
	Status     string
	Platform   string
	CreatedAt  time.Time
	ApprovedAt sql.NullTime
	RejectedAt sql.NullTime
	InvitedAt  sql.NullTime
}
