// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: testers.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const approveTester = `-- name: ApproveTester :exec
UPDATE tester_signups
SET status = 'approved',
    approved_at = NOW(),
    rejected_at = NULL
WHERE id = $1
`

func (q *Queries) ApproveTester(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, approveTester, id)
	return err
}

const createSignup = `-- name: CreateSignup :exec
INSERT INTO tester_signups (email, name, platform)
VALUES ($1, $2, $3)
    ON CONFLICT (email) DO NOTHING
`

type CreateSignupParams struct {
	Email    string
	Name     string
	Platform string
}

func (q *Queries) CreateSignup(ctx context.Context, arg CreateSignupParams) error {
	_, err := q.db.ExecContext(ctx, createSignup, arg.Email, arg.Name, arg.Platform)
	return err
}

const findTesterByID = `-- name: FindTesterByID :one
SELECT id, email, name, platform, status, created_at, approved_at, rejected_at, invited_at
FROM tester_signups
WHERE id = $1
`

type FindTesterByIDRow struct {
	ID         uuid.UUID
	Email      string
	Name       string
	Platform   string
	Status     string
	CreatedAt  time.Time
	ApprovedAt sql.NullTime
	RejectedAt sql.NullTime
	InvitedAt  sql.NullTime
}

func (q *Queries) FindTesterByID(ctx context.Context, id uuid.UUID) (FindTesterByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findTesterByID, id)
	var i FindTesterByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Platform,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.InvitedAt,
	)
	return i, err
}

const listTesters = `-- name: ListTesters :many
SELECT id, email, name, platform, status, created_at, approved_at, rejected_at, invited_at
FROM tester_signups
ORDER BY created_at DESC
`

type ListTestersRow struct {
	ID         uuid.UUID
	Email      string
	Name       string
	Platform   string
	Status     string
	CreatedAt  time.Time
	ApprovedAt sql.NullTime
	RejectedAt sql.NullTime
	InvitedAt  sql.NullTime
}

func (q *Queries) ListTesters(ctx context.Context) ([]ListTestersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTesters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTestersRow
	for rows.Next() {
		var i ListTestersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Platform,
			&i.Status,
			&i.CreatedAt,
			&i.ApprovedAt,
			&i.RejectedAt,
			&i.InvitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTesterInvited = `-- name: MarkTesterInvited :exec
UPDATE tester_signups
SET status = 'invited',
    invited_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkTesterInvited(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markTesterInvited, id)
	return err
}

const rejectTester = `-- name: RejectTester :exec
UPDATE tester_signups
SET status = 'rejected',
    rejected_at = NOW()
WHERE id = $1
`

func (q *Queries) RejectTester(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, rejectTester, id)
	return err
}
